export default {
    DIST_UI_FILE: 'EXT_DIST.built.ui.js',
    DIST_ONLOAD_FILE: 'EXT_DIST.built.onload.js',
    EXTENT_BACKGROUND_PUBLISHER: 'EXTENT_BACKGROUND_PUBLISHER',
    EXTENT_BACKGROUND_API_TIMEOUT: 'EXTENT_BACKGROUND_API_TIMEOUT',
    EXTENT_BACKGROUND_API_INBOUND: 'EXTENT_BACKGROUND_API_INBOUND',
    EXTENT_BACKGROUND_TYPE_ACTION: 'EXTENT_BACKGROUND_TYPE_ACTION',
    EXTENT_CONFIG_STORE: 'EXTENT_CONFIG_STORE',
    MSG_NO_CONFIG_DATA_FOUND: 'Config data not stored in browser yet',
    MSG_STALE_CONFIG_DATA_FOUND: 'Config data was found but is old',
    DOM_ID_UI_MOUNT: 'extento-dom-node',
    DOM_ID_SHADOW_ROOT: 'extento-shadow-node',
    BASE_Z_INDEX: 100000000000000,
};
